#version 300 es

// Nonlinear raytracer for a Schwarzschild black hole.
// This is a port of GpuSchwarzschildRayProcessor.RenderKernel (and the Schwarzschild Hit()
// logic of each hitable) from the C# project. Each fragment traces one ray.
//
// The scene is not stored in uniforms: renderer.js generates the testHitables() function,
// with one hit*() call per hitable and its parameters baked in as constants, and appends it
// to this source. That lets the shader compiler specialize the code for each hitable, which
// is several times faster than looping over an array of hitables.

precision highp float;
precision highp int;

#define MAX_ITERATIONS_LIMIT 10000

// Texture slots; must match scene.js.
const int TEX_NONE = 0;
const int TEX_SKY = 1;
const int TEX_EARTH = 2;
const int TEX_MARS = 3;
const int TEX_DISK = 4;
const int TEX_STAR = 5;
// Not a texture: the procedural grid shown when the sky is hidden, or still loading.
const int TEX_SKY_GRID = 6;

const float PI = 3.14159265358979;
const float TWO_PI = 6.28318530717959;
const float STEP_SIZE = 0.16;
const float STEP_SIZE_OVER_30 = STEP_SIZE / 30.0;
// Refractive index of the glass spheres.
const float GLASS_IOR = 1.5;
const float CHECKER_SIZE = 1.04719;      // Pi / 3
const float HALF_CHECKER_SIZE = 0.52359; // Pi / 6

uniform vec2 uResolution;
uniform vec3 uCameraPosition;
uniform vec3 uCameraLeft;
uniform vec3 uCameraUp;
uniform vec3 uCameraFront;
uniform float uTanFov;
uniform float uPotentialCoefficient;
uniform int uMaxIterations;

uniform sampler2D uSkyTexture;
uniform sampler2D uEarthTexture;
uniform sampler2D uMarsTexture;
uniform sampler2D uDiskTexture;
uniform sampler2D uStarTexture;
// Textures load in the background; until the sky has, the grid is shown in its place.
uniform bool uSkyLoaded;

out vec4 fragColor;

// State of the current ray, shared by the hit*() functions.
vec3 point;
vec3 velocity;
vec3 prevPoint;
float sqrNorm;
float prevSqrNorm;
float potH2;

// Color accumulated from translucent hits (disks, reflections).
vec3 tint = vec3(0.0);
bool hasTint = false;

// The hit that ends the ray. Its texture lookup is deferred until after tracing, where
// control flow is uniform and screen-space derivatives (for mipmapping) are valid.
bool stop = false;
int finalTexture = TEX_NONE;
vec2 finalUv = vec2(0.0);
vec3 finalColor = vec3(0.0);
// Direction in which the ray escaped to the sky, for the sky grid.
vec3 skyDirection = vec3(0.0, 0.0, 1.0);

// Generated by renderer.js: tests the ray against every hitable in the scene, in order.
void testHitables();

// One step of the Schwarzschild geodesic equation (see SchwarzschildBlackHoleEquation).
float stepRay(inout vec3 p, inout vec3 v, float h) {
    p += v * h;
    float lsq = dot(p, p);
    float f1 = potH2 * h / (lsq * lsq * sqrt(lsq));
    v += p * f1;
    return lsq;
}

// Binary search for the step size at which the ray, starting at prevPoint, first satisfies
// the given condition. The step size range and precision match the C# IntersectionSearch.
#define INTERSECTION_SEARCH(result, condition) {                          \
        float stepLow = 0.0;                                              \
        float stepHigh = STEP_SIZE;                                       \
        for (int searchIter = 0; searchIter < 32; searchIter++) {         \
            float stepMid = (stepLow + stepHigh) * 0.5;                   \
            result = prevPoint;                                           \
            vec3 tempVelocity = velocity;                                 \
            float lsq = stepRay(result, tempVelocity, stepMid);           \
            if (abs(stepHigh - stepLow) < 0.00001) {                      \
                break;                                                    \
            }                                                             \
            if (condition) {                                              \
                stepHigh = stepMid;                                       \
            } else {                                                      \
                stepLow = stepMid;                                        \
            }                                                             \
        }                                                                 \
    }

// Same as Util.ToSpherical: returns (r, theta, phi).
vec3 toSpherical(vec3 p) {
    float r = length(p);
    return vec3(r, acos(clamp(p.z / r, -1.0, 1.0)), atan(p.y, p.x));
}

bool checker(float a) {
    return mod(a, CHECKER_SIZE) < HALF_CHECKER_SIZE;
}

// Same as Util.AddColor: blend a hit color with the color accumulated so far (the tint).
vec3 addColor(vec3 hitColor, vec3 tintColor, bool hasTintColor) {
    if (!hasTintColor) {
        return hitColor;
    }
    float brightness = (max(max(tintColor.r, tintColor.g), tintColor.b) + min(min(tintColor.r, tintColor.g), tintColor.b)) * 0.5;
    return min((1.0 - brightness) * hitColor + tintColor * (255.0 / 205.0), vec3(1.0));
}

void addTint(vec3 color) {
    tint = addColor(color, tint, hasTint);
    hasTint = true;
}

// Sky.Hit: has the ray escaped to infinity?
void hitSky(float radiusSqr, int texture) {
    if (sqrNorm > radiusSqr) {
        vec3 s = toSpherical(point);
        finalTexture = texture;
        finalUv = vec2(s.z / TWO_PI, s.y / PI);
        skyDirection = point / sqrt(sqrNorm);
        stop = true;
    }
}

// Horizon.Hit: has the ray fallen past the horizon?
void hitHorizon(bool checkered) {
    if (prevSqrNorm > 1.0 && sqrNorm < 1.0) {
        vec3 c;
        INTERSECTION_SEARCH(c, lsq < 1.0)
        vec3 s = toSpherical(c.xzy);
        finalColor = checkered && (checker(s.y) != checker(s.z)) ? vec3(0.0, 128.0 / 255.0, 0.0) : vec3(0.0);
        stop = true;
    }
}

// Disk.Hit: did we cross the horizontal plane within the disk? Doesn't stop the ray.
void hitDisk(float innerRadius, float outerRadius, vec3 top1, vec3 top2, vec3 bottom1, vec3 bottom2, int texture) {
    float side = prevPoint.y > 0.0 ? -1.0 : prevPoint.y < 0.0 ? 1.0 : 0.0;
    if (point.y * side < 0.0) {
        return;
    }
    vec3 c;
    INTERSECTION_SEARCH(c, side * c.y > 0.0)
    float cSqr = dot(c, c);
    if (cSqr < innerRadius * innerRadius || cSqr > outerRadius * outerRadius) {
        return;
    }
    vec3 s = toSpherical(c);
    // Note: the disk's texture angle is theta, not phi (matching Disk.Hit).
    float angle = s.y + PI / 12.0;
    if (texture == TEX_DISK) {
        // Same as DiscMapping. This hit doesn't end the ray, so it isn't in uniform control
        // flow, and can't use derivatives for mipmapping; sample a fixed level instead.
        vec2 uv = vec2(angle / TWO_PI, (s.x - innerRadius) / (outerRadius - innerRadius));
        addTint(textureLod(uDiskTexture, uv, 1.0).rgb);
    } else {
        bool check = checker(angle);
        addTint(side < 0.0 ? (check ? top1 : top2) : (check ? bottom1 : bottom2));
    }
}

// Sphere.Hit (and CheckeredSphere, TexturedSphere).
void hitSphere(vec3 center, float radiusSqr, vec3 color1, vec3 color2, int texture, float textureOffset) {
    vec3 d = point - center;
    if (dot(d, d) >= radiusSqr) {
        return;
    }
    vec3 c;
    INTERSECTION_SEARCH(c, dot(c - center, c - center) < radiusSqr)
    vec3 n = normalize(center - c);
    vec3 s = toSpherical(vec3(n.x, n.z, -n.y));
    if (texture != TEX_NONE) {
        finalTexture = texture;
        finalUv = vec2((s.z + textureOffset) / TWO_PI, s.y / PI);
    } else {
        finalColor = checker(s.y) != checker(s.z) ? color1 : color2;
    }
    stop = true;
}

// ReflectiveSphere.Hit: reflects the ray, and darkens it slightly.
void hitReflectiveSphere(vec3 center, float radiusSqr) {
    vec3 d = point - center;
    if (dot(d, d) >= radiusSqr) {
        return;
    }
    vec3 c;
    INTERSECTION_SEARCH(c, dot(c - center, c - center) < radiusSqr)
    point = c;
    velocity = reflect(velocity, normalize(point - center));
    addTint(vec3(8.0 / 255.0));
}

// Glass sphere: refracts the ray into the sphere, and out the other side. (Not in the C#
// project.) Inside the sphere the ray is taken to travel in a straight line: over the width
// of a small sphere, the bending by the black hole is negligible.
void hitGlassSphere(vec3 center, float radiusSqr) {
    vec3 d = point - center;
    if (dot(d, d) >= radiusSqr) {
        return;
    }
    vec3 entry;
    INTERSECTION_SEARCH(entry, dot(entry - center, entry - center) < radiusSqr)

    // The ray's speed (the length of velocity) isn't exactly 1, so refract the direction,
    // and keep the speed.
    float speed = length(velocity);
    vec3 direction = refract(velocity / speed, normalize(entry - center), 1.0 / GLASS_IOR);

    // Where the straight path through the sphere comes out again: solving
    // |entry + t * direction - center|^2 = radius^2, with entry on the surface.
    vec3 exit = entry - 2.0 * dot(entry - center, direction) * direction;

    // By symmetry, the ray meets the far side at the same angle it was refracted to, so it
    // always gets out (no total internal reflection). refract() returns zero if it doesn't,
    // though, which rounding error could cause at grazing angles; carry straight on then.
    vec3 outward = refract(direction, -normalize(exit - center), GLASS_IOR);
    if (dot(outward, outward) > 0.0) {
        direction = outward;
    }

    point = exit;
    velocity = direction * speed;
    // The bending depends on the ray's angular momentum around the black hole, which is
    // constant along a free path, but changed by the refraction.
    vec3 h = cross(point, velocity);
    potH2 = uPotentialCoefficient * dot(h, h);

    // A slight blue-green tint, like the edge of a pane of glass.
    addTint(vec3(4.0, 10.0, 9.0) / 255.0);
}

// The sky grid: dark gray, with faint lines of latitude and longitude every 15 degrees, with
// the equator in the plane of the disk. Must be called in uniform control flow, since it uses
// screen-space derivatives to draw the lines one pixel wide, without aliasing.
const vec2 SKY_GRID_CELLS = vec2(24.0, 12.0); // 360 / 15 and 180 / 15
vec3 skyGrid(vec3 direction) {
    vec2 uv = vec2(atan(direction.z, direction.x) / TWO_PI, asin(clamp(direction.y, -1.0, 1.0)) / PI);
    // Size of a pixel, in grid cells. (Longitude wraps from 0.5 to -0.5; see seamlessDerivative.)
    vec2 pixel = vec2(min(fwidth(uv.x), fwidth(fract(uv.x + 0.5))), fwidth(uv.y)) * SKY_GRID_CELLS;
    // Distance to the nearest line, in grid cells.
    vec2 lineDistance = abs(fract(uv * SKY_GRID_CELLS + 0.5) - 0.5);
    vec2 line = clamp(1.0 - lineDistance / max(pixel, 1e-6), 0.0, 1.0);
    // Where lines would be denser than a few pixels apart (near the poles, and where lensing
    // squeezes the sky), fade them out rather than let them turn into noise.
    line *= 1.0 - smoothstep(0.1, 0.3, pixel);
    return mix(vec3(0.05), vec3(0.16), max(line.x, line.y));
}

// Picks the smaller of the two possible u derivatives, so that the seam where u wraps
// from 1 to 0 doesn't select a blurry mip level (Tarini's method).
float seamlessDerivative(float d1, float d2) {
    return abs(d1) < abs(d2) ? d1 : d2;
}

void main() {
    // Camera ray, same as the C# tracers (view vector transformed by the camera basis).
    float aspectRatio = uResolution.y / uResolution.x;
    vec2 ndc = gl_FragCoord.xy / uResolution - 0.5;
    vec3 view = uCameraLeft * (ndc.x * uTanFov) + uCameraUp * (ndc.y * aspectRatio * uTanFov) + uCameraFront;

    velocity = normalize(view);
    point = uCameraPosition;
    sqrNorm = dot(point, point);
    vec3 h = cross(point, velocity);
    potH2 = uPotentialCoefficient * dot(h, h);

    for (int iter = 0; iter < MAX_ITERATIONS_LIMIT; iter++) {
        if (iter >= uMaxIterations || stop) {
            break;
        }
        prevPoint = point;
        prevSqrNorm = sqrNorm;
        sqrNorm = stepRay(point, velocity, sqrt(dot(point, point)) * STEP_SIZE_OVER_30);
        testHitables();
    }

    // Texture derivatives, computed in uniform control flow.
    vec2 dx = dFdx(finalUv);
    vec2 dy = dFdy(finalUv);
    dx.x = seamlessDerivative(dx.x, dFdx(fract(finalUv.x + 0.5)));
    dy.x = seamlessDerivative(dy.x, dFdy(fract(finalUv.x + 0.5)));
    // Neighboring pixels may have hit a different object entirely; don't let that blur the edge.
    dx = clamp(dx, -0.02, 0.02);
    dy = clamp(dy, -0.02, 0.02);

    // Computed for every pixel, since it needs uniform control flow; only used for the sky.
    vec3 gridColor = skyGrid(skyDirection);
    if (finalTexture == TEX_SKY && !uSkyLoaded) {
        finalTexture = TEX_SKY_GRID;
    }

    vec3 hitColor = finalColor;
    if (finalTexture == TEX_SKY_GRID) {
        hitColor = gridColor;
    } else if (finalTexture == TEX_SKY) {
        hitColor = textureGrad(uSkyTexture, finalUv, dx, dy).rgb;
    } else if (finalTexture == TEX_EARTH) {
        hitColor = textureGrad(uEarthTexture, finalUv, dx, dy).rgb;
    } else if (finalTexture == TEX_MARS) {
        hitColor = textureGrad(uMarsTexture, finalUv, dx, dy).rgb;
    } else if (finalTexture == TEX_STAR) {
        hitColor = textureGrad(uStarTexture, finalUv, dx, dy).rgb;
    }

    // Rays that never finish (grazing the photon sphere) keep whatever color they accumulated.
    vec3 color = stop ? addColor(hitColor, tint, hasTint) : tint;
    fragColor = vec4(color, 1.0);
}
